### ISSUE TITLE
TRANSLATION_GUIDE.md 추가

### ISSUE THREAD

**Issue by spongebob03** [PyTorchKorea/hub-kr#18]
## 이슈 내용
같은 분야의 다른 문서들에서 반복되는 내용들이 많습니다.
TRANSLATION_GUIDE.md 문서를 통해 허브 문서 번역 규칙과 겹치는 문장에 대한 템플릿 제시되면 좋을거 같습니다. 

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._
[허브 Vision 모델 번역 중 겹치는 문장별 번역 정리](https://dev01.notion.site/77d7dd5e78194ebf8dc34ed78fec768f)

**Comment by Taeyoung96** [comment]
#79   
추가를 완료하였으므로 issue를 close하도록 하겠습니다.
