### ISSUE TITLE
CONTRITUBING.md 내 번역 관련 내용 수정

### ISSUE THREAD

**Issue by yh00214** [PyTorchKorea/hub-kr#28]
## 이슈 내용
_어떤 이슈인지 알려주세요._

CONTRIBUTING.md 내에서 파이토치 허브 번역에 관련된 내용에 대해, 컨트리뷰터 분들께서 좀 더 쉽게 이해하고 따라할 수 있도록 규칙과 가이드 등을 수정하고자 합니다.

**Comment by Taeyoung96** [comment]
기여에 감사드립니다.
