### ISSUE TITLE
pytorch_vision_alexnet.md 번역 예정

### ISSUE THREAD

**Issue by lsh3163** [PyTorchKorea/hub-kr#3]
문서 URL
번역을 하실 / 요청하실 URL을 남겨주세요.

URL: https://pytorch.kr/hub/pytorch_vision_alexnet/
(대략적인) 예상 완료 일정
예상하시는 완료 일정이 있으시다면 알려주세요. (예. 1달 내, 12월 중 등)

(반드시 지키셔야 하는 일정이 아닙니다 - 일정이 너무 늦어질 경우 다른 번역자를 위해 남겨주세요.)

예상 완료 일정: 다음 주(9/28) 내로 번역 초안 올리도록 하겠습니다.
관련 이슈
현재 번역 요청 / 진행 내역을 보기 위해 각 버전의 메인 이슈를 참조합니다.

(특별한 일이 없다면 변경하지 않으셔도 됩니다.)

**Comment by Taeyoung96** [comment]
@lsh3163   
따로 PR이 없으므로 해당 Issue는 닫도록 하겠습니다!
