### ISSUE TITLE
TRANSLATION_GUIDE.md를 개선 및 추가하기 위한 가이드

### ISSUE THREAD

**Issue by mindongjun** [PyTorchKorea/hub-kr#30]
### 튜토리얼, 허브의 통일된 번역(용어 관리)을 위한 가이드 부재

- 번역(용어 관리)를 위한 별도의 종합 레포 고려안
    - 별도 레포 사용시  번역관련 용어 추가 / 이의제기 등 이슈 관리의 용이함
    - 별도 레포가 아니더라도 라벨 관리 및 위키로 관리하는 방법도 고려 
        - 깃헙 위키의 경우 hierarchy 관리는 쉽지 않았다는 단점 존재

## 추가 정보
_다른 참고할 정보 또는 URL 등이 있다면 알려주세요._

**Comment by Taeyoung96** [comment]
#79 에서 반영된 issue이므로 close하도록 하겠습니다.
